language: c
compiler:
  - gcc
  - clang

sudo: required

install:
  - sudo -H apt-get -q -qq -y update
  - sudo -H apt-get -q -qq -y install libc6-dev uuid-dev libpam0g-dev libcurl4-openssl-dev dh-autoreconf autotools-dev clang cmake pkg-config texinfo libssl-dev
  - sudo -H ./ci/dependencies.sh

script:
  - make

notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - lighthauz:L9vNoLRwptkWOXxmnX7ztYjQ#travis-ci
